### ISSUE TITLE
kotlinx.atomicfu.transformer.TransformerException

### ISSUE THREAD

**Issue by GeorgePap-719** [Kotlin/kotlinx-atomicfu#293]
Trying to create an a data structure with atomicfu and im getting an error during compilation phase:

Mini test to reproduce it:
```kotlin
class ArrayQueueTest {
    @Test
    fun testAtomicFU() {
        val test = SomeClass()
    }

    class SomeClass {
        private val array: Array<AtomicRef<QueueJob?>> = Array(10) { atomic(null) }
    }
}

typealias QueueJob = suspend CoroutineScope.() -> Deferred<Any?>
```

This is also reproduceable with different type other than `QueueJob`:
```kotlin
   class SomeClass {
        private val array: Array<AtomicInt> = Array(10) { atomic(0) }
    }
```

So i think it is reproduceable with any T in Array. 

stacktrace:
```
> Task :wrapper
BUILD SUCCESSFUL in 182ms
1 actionable task: 1 executed
> Task :processResources NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :classes UP-TO-DATE
> Task :transformAtomicfuClasses UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :compileTestKotlin
w: file:///home/geolab/workspaces/personal/asyn-request-queue-problem/asyn-request-queue-problem/src/test/kotlin/ArrayQueueTest.kt:29:13 Variable 'test' is never used
> Task :compileTestJava NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :transformTestAtomicfuClasses FAILED
ArrayQueueTest.kt: asynqueueproblem.test.ArrayQueueTest$SomeClass::<init>: factory kotlinx.atomicfu.AtomicFU::atomic invocation must be followed by putfield
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':transformTestAtomicfuClasses'.
> kotlinx.atomicfu.transformer.TransformerException: Encountered errors while analyzing references
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 969ms
6 actionable tasks: 3 executed, 3 up-to-date
```

Original code is in https://github.com/GeorgePap-719/asyn-request-queue-problem/blob/atomicFU-error/src/test/kotlin/ArrayQueueTest.kt

possibly related somehow to  #89

**Comment by mvicsokolova** [comment]
There are two concerns regarding this problem:
- Please, refrain from using legacy bytecode transformer and switch to the compiler plugin transformations. Compiler plugin transformations are more reliable and provide better error messages. To enable them, please set the property `kotlinx.atomicfu.enableJvmIrTransformation=true` in your `gradle.properties` file as stated in the README (https://github.com/Kotlin/kotlinx-atomicfu#atomicfu-compiler-plugin).

- Use atomic array API provided by the library instead of declaring your own array of atomics (`kotlinx.atomicfu.AtomicArray`). There is a factory function `atomicArrayOfNulls<T>` that will create an array of atomic values initialized with nulls. For your example, 

```
class SomeClass {
  private val array = atomicArrayOfNulls<QueueJob>(10)
}
```
